sudo: required
services:
  - docker

before_install:
  - docker build -t sdrpaladu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sdrpaladu/react-test npm test -- --coverage # -- --coverage means -> exit with coverage results

after_success:
  - docker build -t sdrpaladu/multi-client ./client
  - docker build -t sdrpaladu/multi-nginx ./nginx
  - docker build -t sdrpaladu/multi-server ./server
  - docker build -t sdrpaladu/multi-worker ./worker

  #Login to docker cli and push these images to docker hub
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  #Push images off to Docker hub
  - docker push sdrpaladu/multi-client
  - docker push sdrpaladu/multi-nginx
  - docker push sdrpaladu/multi-server
  - docker push sdrpaladu/multi-worker